- components/WebView.qml
- plugin.cpp
All default protocol handlers are disabled by default as
navigation must be disabled within html emails.
> [sailfish-components-webview] Add linkClicked signal. Contributes to JB#36016

- import/webview/OrientationFader.qml
- import/webview/WebView.qml
- import/webview/WebViewPage.qml
- import/webview/plugin.cpp
- import/webview/plugin.h
- import/webview/qmldir
- import/webview/webview.pro
- rpm/sailfish-components-webview.spec
This commit adds a virtual keyboard observer to the WebView to ensure
that we don't relayout its content while the VKB animates.
Contributes to JB#36163
> [sailfish-components-webview] Don't relayout content while VKB animates. Contributes to JB#36163

- import/webview/plugin.cpp
Lanscape virtual keyboard handling was broken. This had nothing to
do with "date" and "time" input types that were mentioned in:
https://github.com/sailfishos/sailfish-components-webview/pull/11
> [sailfish-components-webview] Calculate "screen size" from current geometry. Contributes to JB#36163

- import/webview/WebView.qml
- import/webview/WebViewFlickable.qml
- import/webview/plugin.cpp
- import/webview/plugin.h
- import/webview/rawwebview.cpp
- import/webview/rawwebview.h
- import/webview/translations.pri
- import/webview/webview.pro
- lib/webenginesettings.cpp
This removes WebViewPage as it is not necessary. It also includes the WebView in the WebViewFlickable, so only WebViewFlickable need be declared. It is available via the `webView` property.
It supports a footer only at the moment until setMargins() successfully sets top margins.
You'll notice that the sync of the footer and the web view is way out and this is due to the `scrollableOffset` updates being really infrequent. We need to get better update frequency in order to keep them more closely synced.
An example:
```
import QtQuick 2.1
import Sailfish.Silica 1.0
import Sailfish.WebView 1.0
import Qt5Mozilla 1.0
ApplicationWindow {
initialPage: Page {
id: page
anchors.fill: parent
WebViewFlickable {
id: flickable
anchors.fill: parent
webView.url: "http://www.wikipedia.org"
footer: …
```
> Make Flickable and WebView get along.

- lib/webenginesettings.cpp
Let's do not tamper QPalette just adjust perference.
@chriadam @jpetrell review. Tested some colors with Martin Schüle and we agreed go with "#878787" that's from roughly half way between white and black. This should cope rather well possible blending cases. Of course selection background can still blend with web content but that's totally different level problem.
> [sailfish-webengine-settings] Update text selection background color. Fixes JB#36973

- import/pickers/MultiImagePicker.qml
- import/pickers/MultiMusicPicker.qml
- import/pickers/MultiVideoPicker.qml
These are not used as DialogHeader titles. As we have search field
visible there as well I think that it is better to cleanup title from
MultiImagePickerDialog, MultiMusicPickerDialog, and MultiVideoPickerDialog
of sailfish-components-pickers rather than adding title here as well.
@jpetrell review ?
> [sailfish-components-webview] Cleanup invisible titles. Contributes to JB#19575

- lib/webenginesettings.cpp
Default values are being used instead.
See also:
https://git.merproject.org/mer-core/gecko-dev/merge_requests/42/
https://github.com/sailfishos/sailfish-browser/pull/571
> Disable async scroll throttle and timeout for now

- lib/webenginesettings.cpp
See: https://github.com/sailfishos/sailfish-browser/issues/580
> [sailfish-webengine] Do not try to floor low pixel ratio values. Fixes JB#40528

- import/webengine/plugin.cpp
The existence (or lack thereof) of a cache has a had an observed effect
on crash occurences. It's probably coincidental but it doesn't really
make sense and may even be detrimental to cache data to disk for most
web view uses which are mostly one-off transactions.
> [webengine] Don't create application caches by default. Contributes to JB#48786

- import/popups/AlertDialog.qml
- import/popups/UserPrompt.qml
According to W3Schools, a javascript alert() dialogue "displays an alert
box with a specified message and an OK button", in contrast with a
confirm() dialogue which also shows a Cancel button.
This change removes the "Cancel" option from the alert() dialogue.
> [webview] Remove "Cancel" from alert() dialogue. Contributes to JB#50018

- import/controls/permissionfilterproxymodel.cpp
- import/controls/permissionfilterproxymodel.h
- import/controls/permissionmodel.cpp
- import/controls/permissionmodel.h
Add ability to clear the proxy model by permission type.
Also, for the correct operation of deleting multiple elements, add the remove method by
host, type and capability. It fix incorrect index errors.
> [sailfish-webview] Add ability remove all items for permission type. Contributes to JB#52493

- tools/generate_property_translations.py
Add translation generation script for property files. This is intended
to be used when engine is updated and the result can be then committed
to a repository. The script outputs a C++ source file.
> [sailfish-webview] Add translation generation script. Fixes JB#53252

- import/popups/DownloadMenuItem.qml
Saving file with spaces results in %20 in url. The handling here
didn't decode, but then removed % on downloadhelper.
-> saved file had spaces replaced with '20'.
Now the saved file doesn't still get spaces as the download helper
replaces whitespace with underscores, but that's a lot better already.
@rainemak
> [components-webview] Fix saving file name with url escaping. Fixes JB#53509

- import/controls/permissionmanager.cpp
- import/controls/permissionmanager.h
Now we have popup notifications, we need to have ability to set permission for the session.
Popup differs from other permissions (ex. geolocation) we don't recieve a request and can't handle it with
checkedDontAsk response. We have to catch popup blocked events ourselves and handle it.
Therefore, adding the capabilities of the PermissionManager is required.
> [sailfish-components-webview] Add ability to set permission for current session. Contributes to JB#52731

- import/popups/PasswordManagerDialog.qml
- import/popups/PopupOpener.qml
The signal is monitored by the sailfish-browser WebView, allowing it to
store favicons for pages with stored login info.
To be used alongside https://github.com/sailfishos/sailfish-browser/pull/836 .
> Signal when a login has been saved

- import/popups/PasswordManagerDialog.qml
The original wording was a bit tricky to parse with both username and domain in the sentence, so the username has been removed.
Some new text explaining how passwords can be managed has been added.
> Update wording on password save pop-up

- examples/custompopups/CustomPromptPopup.qml
- import/popups/PopupOpener.qml
- import/popups/PromptDialog.qml
- import/popups/PromptPopupInterface.qml
When passed a default value to be prefilled into the prompt input
field, we should set the input field's text value to that value.
In order to prevent two-way-binding problem, we need to pass this
default value as a separate input property, rather than attempting
to bind it to the (output) value property.
> [sailfish-components-webview] Prefill prompt input field with default value. Contributes to JB#52387 OMP#JOLLA-257

- import/popups/PopupOpener.qml
The prefill value is passed as "checked" not as "value", according
to 0279c8930f1dcac9076503db63a1ee94b7ca9e0a in embedlite-components.
(Note also the typo: "addional" in embedlite-components.)
> [sailfish-components-webview] Appropriately detect preventAdditionalDialogs prefill value. Contributes to JB#55035

- doc/sailfish-webview.qdocconf
The overlapping index title caused unwanted pages to appear in top
level index.
> [sailfish-webview] Remove classes from top level index. Fixes JB#55581

- doc/sailfish-webview-popups-locationpopupinterface.qdoc
- import/popups/LocationDialog.qml
- import/popups/LocationPopupInterface.qml
- import/popups/PopupOpener.qml
A `privateBrowsing` flag is now passed with the "embed:permissions" message when the browser wants to request a permission of the user (a location permission specifically).
This change disables the option to store the permission when private browsing is enabled, to avoid leaking location data.
> Act on private browsing when requesting permissions. JB#55925 OMP#JOLLA-445

- import/popups/PopupOpener.qml
A (rather embarrassing; sorry!) logic error meant that the permission dialogue thought it was always in private browsing mode, preventing the user from saving their geolocation permission setting.
Since the `privateBrowsing` entry will always be included in the message data, there should be no need to guard it anyway.
> Ensure geo permissions can be saved in normal browsing. Fixes JB#56207 OMP#JOLLA-509

- import/controls/permissionmodel.cpp
If a permission isn't one of the permissions we are aware of (and
have an icon for) don't include it in the permissions model which
exposes it to QML.
Contributes to JB#56450
> [sailfish-components-webview] Only populate permissions model with known permissions. Contributes to JB#56450 OMP#JOLLA-550

- import/webview/rawwebview.cpp
Browsing context cannot be optional for sub windows.
> [webview] Align to ViewCreator API changes. JB#56631 OMP#JOLLA-569

- doc/sailfish-webview-webenginesettings.cpp
- doc/sailfish-webview-webenginesettings.h
- doc/sailfish-webview-webenginesettings.qdoc
From QML point of view we can have setPreference documented as one method with one optional argument.
> Document overloaded setPreference C++ method

- lib/webenginesettings.cpp
The default values for these settings have now been moved to embedding.js in gecko-dev.
embedlite.azpc.handle.singletap
embedlite.azpc.handle.longtap
embedlite.azpc.json.viewport
embedlite.azpc.json.singletap
embedlite.azpc.json.longtap
Other embedlite.azpc.* settings can also be found there.
> Remove embedlite.azpc.json.* forced defaults. JB#56765 OMP#JOLLA-607

- lib/lib.pro
- lib/logging.cpp
- lib/logging.h
- lib/webenginesettings.cpp
WebAssembly, and in particular the baselinejit, seems to have a heavy
memory footprint, which can cause the browser to crash on lower memory
devices (approx 2Gb or lower).
This change automatically disables wasm_baselinejit on devices with less
than 2.5Gb of RAM.
> Disable wasm_baselinejit on lower memory devices. JB#56635 OMP#JOLLA-572

- import/webview/WebView.qml
If the ypos and height of the WebView don't reach the base of the page, then the keyboard height must be compensated to adjust.
This is especially important in case a widget changes height when the keyboard opens, to avoid the margin being added twice.
> [components-webview] Adjust keyboard margin based on position. JB#57689

- doc/index.qdoc
- doc/sailfish-webview.qdocconf
Adds a description to the docs of three different approaches that can be used for serving local content using a WebView, in order to avoid Cross Origin Resource Sharing protection issues.
> [webview-docs] Elaborate on using local content with CORS protection. Fixes JB#57956

- doc/sailfish-webview-webenginesettings.cpp
- doc/sailfish-webview-webenginesettings.h
- doc/sailfish-webview-webenginesettings.qdoc
- lib/webenginesettings.cpp
- lib/webenginesettings.h
Sends an "ambience-theme-changed" notification with either "dark" or "light" data when the ambience changes, to be picked up by gecko.
Adds C++ and QML documentation to cover the WebEngineSettings::doNotTrack and WebEngineSettings::colorScheme properties.
Also amends the property brief text for other properties, to make them work better on the C++ page, where the brief text is automatically prefixed with the text "This property holds ".
> [webview-docs] Add docs for doNotTrack and colorScheme. JB#58394

- import/controls/TextSelectionController.qml
- lib/webenginesettings.cpp
- lib/webenginesettings.h
- lib/webenginesettings_p.h
- rpm/sailfish-components-webview.spec
These are the further changes I've needed to make to get the WebView working with the latest ESR 91 build. This adds two commits on top of  #168.
The first commit is to set the preferences as needed.
The second commit is to revert to the previous ofono import. I expect this second commit is only needed because of the SDK version I'm using (or maybe because I wasn't on devel?) and so almost certainly needs to be removed. I'm including it for completeness.
The first commit might be unnecessary as well?
> Changes needed for ESR 91

- import/popups/ContextMenu.qml
The expanding item in the middle didn't take into account that the Column also uses a bit of height for spacings. Simplified the setup a bit too.
> [components-webview] Avoid small scrollable area on landscape context menu. JB#63257

- examples/custompopups/CustomAlertPopup.qml
- examples/custompopups/CustomAuthPopup.qml
- examples/custompopups/CustomBlockedTabPopup.qml
- examples/custompopups/CustomConfirmPopup.qml
- examples/custompopups/CustomLocationPopup.qml
- examples/custompopups/CustomPasswordManagerPopup.qml
- examples/custompopups/CustomPromptPopup.qml
- examples/custompopups/custompopups.pro
- examples/custompopups/main.qml
- examples/examples.pro
- examples/webview-test-app/SpinBox.qml
- examples/webview-test-app/main.qml
- examples/webview-test-app/webview-test-app.pro
- import/webview/WebView.qml
- import/webview/rawwebview.cpp
Depends on https://github.com/sailfishos/qtmozembed/pull/58 to have properly working text selection.
Some cleaning up  while at it too. Separate commits.
> Webview landscape display fixing
