import/WebView.qml
Do not generate unique ids rather use the uniqueID of the
webview.
=> Fix unique id usage

import/popups/AuthDialog.qml
Port Joona's commit SHA1 cc1d81b06c6 from Sailfish Browser
Original author: Joona Petrell <joona.petrell@jollamobile.com>
See original commit: https://github.com/sailfishos/sailfish-browser/commit/cc1d81b06c654fbbd6bb3105e2b028a73bc6db59
=> [sailfish-components-webview] Allow toggling authentication dialog password visibility. Contributes to JB#33148

import/popups/GeolocationHosts.js, import/popups/PopupOpener.qml, import/popups/popups.pro, rpm/sailfish-components-webview.spec
@jpetrell , @chriadam , @pvuorela review ?
=> [sailfish-components-webview] Share geolocation responses across tabs.  Fixes JB#36975

import/popups/ContextMenu.qml, import/popups/ShareLinkPage.qml, import/popups/ShareTextPage.qml, import/popups/UserPrompt.qml
=> [components-webview] Use common sharing page. Contributes to JB#41068

rpm/sailfish-components-webview.spec
Maybe also tag as 1.0.0 so library file names stay compatible?
=> [sailfish-components-webview] Fixed pkgconfig version, contributes to jb#38551

rpm/sailfish-components-webview.spec
=> [sailfish-components-webview] Correct license. Contributes to JB#45486

import/pickers/PickerCreator.qml, import/pickers/PickerOpener.qml
Requires:
https://git.sailfishos.org/mer-core/embedlite-components/merge_requests/52
=> [sailfish-components-webview] Align file picking to the new parameters. JB#49804

import/popups/PopupOpener.qml
=> [sailfish-components-webview] Always display geolocation prompt dialog when geolocation permission is requested. Contributes to JB#51932

import/controls/permissionfilterproxymodel.cpp, import/controls/permissionfilterproxymodel.h, import/controls/permissionmodel.cpp
If you want to add new exception to permission model, you need make sure that it doesn't
have for this host. Otherwise, change capability for this host.
=> [sailfish-webview] Append add method to proxyModel and setCapability if host already exist. Contributes to JB#52422

doc/doc.pro, doc/index.qdoc, doc/sailfish-webview-rawwebview.qdoc, doc/sailfish-webview-webview.qdoc, doc/sailfish-webview-webviewflickable.qdoc, doc/sailfish-webview-webviewpage.qdoc, doc/sailfish-webview.cpp, doc/sailfish-webview.qdocconf, lib/downloadhelper.cpp, lib/webengine.cpp, rpm/sailfish-components-webview.spec, sailfish-components-webview.pro
Currently just adds some scaffolding to be populated with the documentation.
=> Add scaffolding for doc generation

import/popups/PopupOpener.qml, import/webview/WebView.qml, import/webview/rawwebview.cpp, rpm/sailfish-components-webview.spec
Requires:
https://git.sailfishos.org/mer-core/qtmozembed/merge_requests/82
=> Align with latest QtMozEmbed

doc/sailfish-webview-webview.qdoc
This is currently on top of https://github.com/sailfishos/sailfish-components-webview/pull/102. Will rebase once PR #102 is merged.
=> Add documentation for the runJavaScript

import/webview/WebView.qml, rpm/sailfish-components-webview.spec
Requires https://git.sailfishos.org/mer-core/qtmozembed/merge_requests/96
=> [webview] Use renamed backgroundColor. JB#54342 OMP#JOLLA-158

import/popups/PopupOpener.qml, import/popups/PopupProvider.qml, import/popups/WebrtcPermissionDialog.qml, import/popups/WebrtcPermissionInterface.qml, import/popups/qmldir
=> [sailfish-webview] Implement WebRTC permission dialog. JB#53947

examples/custompopups/CustomPromptPopup.qml, import/popups/PromptDialog.qml
The binging doesn't work for some reason
=> [sailfish-components-webview] Fix for input prompts. Fixes JB#54845 OMP#JOLLA-231

doc/doc.pro, rpm/sailfish-components-webview.spec
=> [components-webview] Migrate to sailfish-qdoc-template. JB#54004

import/controls/TextSelectionController.qml
This PR also reverts c2521083b005287e08e5d217642089961f206385.
=> Adjust text selection handles by visual viewport offset

LICENSE.txt, rpm/sailfish-components-webview.spec
=> [components-webview] Add license file. JB#55991

import/popups/ContextMenu.qml
Test case here:
https://github.com/sailfishos/sailfish-browser/pull/980
=> [webview-popups] Allow copying link text to clipboard. Fixes JB#37245

import/webview/WebView.qml
Removes a debug variable that erroneously slipped into the code.
=> [components-webview] Fix keyboard margin calculation. JB#57689

import/controls/TextSelectionController.qml, rpm/sailfish-components-webview.spec
Also dependency was missing.
@mlehtima
=> [components-webview] Migrate to new qofono import. JB#59690

import/popups/ContextMenu.qml
~~Change max line count to 4 and reduce font size to large.~~
This commit also reduces font size to large.
=> [components-webview] Add expander to context menu title. JB#61064

lib/downloadhelper.cpp, lib/lib.pro, lib/webengine.h, lib/webenginesettings.h, rpm/sailfish-components-webview.spec, tests/auto/auto.pro, tests/tests.pro
=> Don't install private logging header. JB#61972

defaults.pri, import/webview/WebView.qml, lib/lib.pro, lib/webengine.cpp, lib/webenginesettings.cpp
- empty private header file removed
- static functions marked properly such
- fixed some typos
- remove c++11 config which is the default already
=> [components-webview] Clean up cruft, fix typos. JB#62702
